-- CreateTable
CREATE TABLE "cards" (
    "id" TEXT NOT NULL,
    "oracle_id" TEXT,
    "multiverse_ids" INTEGER[],
    "mtgo_id" INTEGER,
    "mtgo_foil_id" INTEGER,
    "tcgplayer_id" INTEGER,
    "tcgplayer_etched_id" INTEGER,
    "cardmarket_id" INTEGER,
    "arena_id" INTEGER,
    "resource_id" TEXT,
    "name" TEXT NOT NULL,
    "lang" TEXT NOT NULL,
    "released_at" DATE NOT NULL,
    "layout" TEXT NOT NULL,
    "highres_image" BOOLEAN NOT NULL,
    "image_status" TEXT NOT NULL,
    "mana_cost" TEXT,
    "cmc" DOUBLE PRECISION NOT NULL,
    "power" TEXT,
    "toughness" TEXT,
    "type_line" TEXT NOT NULL,
    "oracle_text" TEXT,
    "flavor_text" TEXT,
    "colors" TEXT[],
    "color_identity" TEXT[],
    "produced_mana" TEXT[],
    "keywords" TEXT[],
    "all_parts" JSONB,
    "card_faces" JSONB,
    "legalities" JSONB NOT NULL,
    "games" TEXT[],
    "finishes" TEXT[],
    "reserved" BOOLEAN NOT NULL,
    "game_changer" BOOLEAN,
    "foil" BOOLEAN NOT NULL,
    "nonfoil" BOOLEAN NOT NULL,
    "oversized" BOOLEAN NOT NULL,
    "promo" BOOLEAN NOT NULL,
    "reprint" BOOLEAN NOT NULL,
    "variation" BOOLEAN NOT NULL,
    "digital" BOOLEAN NOT NULL,
    "full_art" BOOLEAN NOT NULL,
    "textless" BOOLEAN NOT NULL,
    "booster" BOOLEAN NOT NULL,
    "story_spotlight" BOOLEAN NOT NULL,
    "set_id" TEXT NOT NULL,
    "set" TEXT NOT NULL,
    "set_name" TEXT NOT NULL,
    "set_type" TEXT NOT NULL,
    "collector_number" TEXT NOT NULL,
    "rarity" TEXT NOT NULL,
    "border_color" TEXT NOT NULL,
    "frame" TEXT NOT NULL,
    "frame_effects" TEXT[],
    "watermark" TEXT,
    "security_stamp" TEXT,
    "promo_types" TEXT[],
    "artist" TEXT,
    "artist_ids" TEXT[],
    "illustration_id" TEXT,
    "card_back_id" TEXT,
    "edhrec_rank" INTEGER,
    "penny_rank" INTEGER,
    "uri" TEXT NOT NULL,
    "scryfall_uri" TEXT NOT NULL,
    "set_uri" TEXT NOT NULL,
    "set_search_uri" TEXT NOT NULL,
    "scryfall_set_uri" TEXT NOT NULL,
    "rulings_uri" TEXT NOT NULL,
    "prints_search_uri" TEXT NOT NULL,
    "prices" JSONB NOT NULL,
    "purchase_uris" JSONB,
    "related_uris" JSONB NOT NULL,
    "preview" JSONB,
    "image_uris" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "cards_pkey" PRIMARY KEY ("id")
);
