services:
  db:
    image: postgres:16-alpine
    container_name: mtg_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mtg
      POSTGRES_PASSWORD: mtg_password
      POSTGRES_DB: mtg_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
